# Generated by Django 5.1.6 on 2025-02-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_phone_number'),
        ('utils', '0007_alter_choice_choice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gender', to='utils.choice'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_status', to='utils.choice'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_type', to='utils.choice'),
        ),
    ]
