# Generated by Django 5.1.6 on 2025-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_of_assignee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
