# Generated by Django 5.1.6 on 2025-02-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
