# Generated by Django 5.1.6 on 2025-02-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lesson_lesson_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionoptions',
            unique_together={('question', 'options')},
        ),
    ]
