# Generated by Django 5.1.6 on 2025-02-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_questionoptions_unique_together'),
        ('utils', '0008_alter_choice_choice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='designation',
            field=models.ForeignKey(blank=True, limit_choices_to={'choice_type': 'designation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee_designation', to='utils.choice'),
        ),
    ]
