# Generated by Django 5.1.6 on 2025-02-26 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_no_of_assignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignee',
            unique_together={('course', 'user')},
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='designation',
        ),
    ]
