# Generated by Django 5.1.6 on 2025-02-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_assignee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='media',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
