# Generated by Django 5.1.6 on 2025-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_lesson_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
        migrations.AddField(
            model_name='question',
            name='is_lesson',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
