# Generated by Django 5.1.6 on 2025-02-27 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_course_course_duration_question_is_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='answer_type',
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_lesson',
        ),
        migrations.AlterField(
            model_name='assignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
