# Generated by Django 5.1.6 on 2025-02-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rename_type_question_answer_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionOptions',
            new_name='Answers',
        ),
    ]
