# Generated by Django 5.1.6 on 2025-02-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_questionoptions_answers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answers',
            table='answers',
        ),
    ]
