# Generated by Django 5.1.6 on 2025-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_choice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_name',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('admin', 'Admin'), ('employee', 'Employee')], max_length=255),
        ),
    ]
