# Generated by Django 5.1.6 on 2025-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_choice_choice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_name',
            field=models.CharField(max_length=255),
        ),
    ]
