# Generated by Django 5.1.6 on 2025-02-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_choice_choice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('USER', 'User'), ('GENDER', 'Gender'), ('STATUS', 'Status')], max_length=255),
        ),
    ]
