# Generated by Django 5.1.6 on 2025-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_choice_choice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('user', 'User'), ('gender', 'Gender'), ('status', 'Status')], max_length=255),
        ),
    ]
